import { useState } from "react";
import { Link } from "react-router-dom";
import { authService } from "@/services/auth.service";
import { Button, Label } from "@/components/ui";

export default function SignUpPage() {
  const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); try { await authService.signUp(email, password, { full_name: fullName }); setMessage("Account created. Check your inbox to verify your email before signing in."); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create account"); } }
  return <main className="min-h-screen grid place-items-center p-6 bg-muted/30"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-2xl border bg-background p-8 shadow-sm"><div><h1 className="text-2xl font-bold">Create your account</h1><p className="mt-2 text-sm text-muted-foreground">Start with your verified work email.</p></div>{message && <p className="rounded-lg bg-emerald-500/10 p-3 text-sm text-emerald-700">{message}</p>}{error && <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="space-y-2"><Label htmlFor="name">Full name</Label><input id="name" required value={fullName} onChange={(e) => setFullName(e.target.value)} className="flex h-10 w-full rounded-lg border bg-background px-3 text-sm" /></div><div className="space-y-2"><Label htmlFor="email">Email address</Label><input id="email" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="flex h-10 w-full rounded-lg border bg-background px-3 text-sm" /></div><div className="space-y-2"><Label htmlFor="password">Password</Label><input id="password" type="password" minLength={8} required value={password} onChange={(e) => setPassword(e.target.value)} className="flex h-10 w-full rounded-lg border bg-background px-3 text-sm" /></div><Button className="w-full">Create account</Button><p className="text-center text-sm text-muted-foreground">Already registered? <Link to="/login" className="text-primary hover:underline">Sign in</Link></p></form></main>;
}
