-- PayrollPro multi-tenant schema. Run in the Supabase SQL editor before deploying the app.
create extension if not exists pgcrypto;
create type public.app_role as enum ('admin', 'hr', 'employee');
create type public.employee_status as enum ('active', 'inactive', 'terminated', 'on-leave');
create type public.request_status as enum ('pending', 'approved', 'rejected', 'cancelled');

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, logo_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, organization_id uuid references public.organizations(id), email text not null, full_name text not null, role public.app_role not null default 'employee', avatar_url text, employee_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.departments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, code text not null, description text, head_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, code));
create table public.designations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, department_id uuid references public.departments(id) on delete set null, title text not null, level integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.employees (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid unique references auth.users(id) on delete set null, employee_id text not null, first_name text not null, last_name text not null, email text not null, phone text, department_id uuid references public.departments(id) on delete set null, designation_id uuid references public.designations(id) on delete set null, joining_date date, employment_type text default 'full-time', status public.employee_status not null default 'active', basic_salary numeric(12,2) not null default 0, photo_url text, bank_details jsonb not null default '{}'::jsonb, compliance_details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, employee_id), unique(organization_id, email));
alter table public.profiles add constraint profiles_employee_id_fkey foreign key (employee_id) references public.employees(id) on delete set null;
create table public.attendance (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, date date not null, status text not null default 'present', check_in timestamptz, check_out timestamptz, working_hours numeric(5,2), remarks text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(employee_id, date));
create table public.leave_types (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, code text not null, annual_allowance numeric(6,2) not null default 0, is_paid boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, code));
create table public.leave_balances (id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.employees(id) on delete cascade, leave_type_id uuid not null references public.leave_types(id) on delete cascade, year integer not null, allocated numeric(6,2) not null default 0, used numeric(6,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(employee_id, leave_type_id, year));
create table public.leave_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, leave_type_id uuid not null references public.leave_types(id), from_date date not null, to_date date not null, days numeric(6,2) not null, reason text not null, status public.request_status not null default 'pending', rejection_reason text, approved_by uuid references auth.users(id), approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(to_date >= from_date));
create table public.payroll_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, month integer not null check(month between 1 and 12), year integer not null, status text not null default 'draft', processed_at timestamptz, paid_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, month, year));
create table public.payslips (id uuid primary key default gen_random_uuid(), payroll_run_id uuid not null references public.payroll_runs(id) on delete cascade, employee_id uuid not null references public.employees(id), gross_salary numeric(12,2) not null default 0, total_deductions numeric(12,2) not null default 0, net_salary numeric(12,2) not null default 0, components jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(payroll_run_id, employee_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, message text not null, type text not null default 'info', read boolean not null default false, created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid references auth.users(id), action text not null, entity text not null, entity_id uuid, changes jsonb, created_at timestamptz not null default now());
create index on public.employees(organization_id, status); create index on public.attendance(employee_id, date); create index on public.leave_requests(organization_id, status); create index on public.notifications(user_id, read);

create or replace function public.current_org_id() returns uuid language sql stable security definer set search_path = public as $$ select organization_id from public.profiles where id = auth.uid() $$;
create or replace function public.is_hr() returns boolean language sql stable security definer set search_path = public as $$ select role in ('admin','hr') from public.profiles where id = auth.uid() $$;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,email,full_name) values (new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1))); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create trigger organizations_updated before update on public.organizations for each row execute procedure public.set_updated_at();
create trigger employees_updated before update on public.employees for each row execute procedure public.set_updated_at();
create trigger departments_updated before update on public.departments for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security; alter table public.organizations enable row level security; alter table public.departments enable row level security; alter table public.designations enable row level security; alter table public.employees enable row level security; alter table public.attendance enable row level security; alter table public.leave_types enable row level security; alter table public.leave_balances enable row level security; alter table public.leave_requests enable row level security; alter table public.payroll_runs enable row level security; alter table public.payslips enable row level security; alter table public.notifications enable row level security; alter table public.audit_logs enable row level security;
-- Organization data is isolated by profile organization. Employees get only their own personnel records.
create policy "profiles self or HR" on public.profiles for select using (id = auth.uid() or (organization_id = current_org_id() and is_hr()));
create policy "profiles self update" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "organization members" on public.organizations for select using (id = current_org_id());
create policy "org read" on public.departments for select using (organization_id = current_org_id()); create policy "hr write departments" on public.departments for all using (organization_id = current_org_id() and is_hr()) with check (organization_id = current_org_id() and is_hr());
create policy "org read designations" on public.designations for select using (organization_id = current_org_id()); create policy "hr write designations" on public.designations for all using (organization_id = current_org_id() and is_hr()) with check (organization_id = current_org_id() and is_hr());
create policy "employees scoped read" on public.employees for select using (organization_id = current_org_id() and (is_hr() or user_id = auth.uid())); create policy "hr write employees" on public.employees for all using (organization_id = current_org_id() and is_hr()) with check (organization_id = current_org_id() and is_hr());
create policy "attendance scoped" on public.attendance for select using (organization_id = current_org_id() and (is_hr() or employee_id in (select id from public.employees where user_id = auth.uid()))); create policy "attendance write" on public.attendance for all using (organization_id = current_org_id() and is_hr()) with check (organization_id = current_org_id() and is_hr());
create policy "leave types org" on public.leave_types for select using (organization_id = current_org_id()); create policy "leave types write" on public.leave_types for all using (organization_id = current_org_id() and is_hr()) with check (organization_id = current_org_id() and is_hr());
create policy "balances scoped" on public.leave_balances for select using (employee_id in (select id from public.employees where organization_id=current_org_id() and (user_id=auth.uid() or is_hr())));
create policy "leaves scoped" on public.leave_requests for select using (organization_id=current_org_id() and (is_hr() or employee_id in (select id from public.employees where user_id=auth.uid()))); create policy "employees create leave" on public.leave_requests for insert with check (organization_id=current_org_id() and employee_id in (select id from public.employees where user_id=auth.uid())); create policy "hr update leaves" on public.leave_requests for update using (organization_id=current_org_id() and is_hr());
create policy "payroll scoped" on public.payroll_runs for select using (organization_id=current_org_id() and is_hr()); create policy "hr write payroll" on public.payroll_runs for all using (organization_id=current_org_id() and is_hr()) with check (organization_id=current_org_id() and is_hr());
create policy "payslips scoped" on public.payslips for select using (employee_id in (select id from public.employees where organization_id=current_org_id() and (user_id=auth.uid() or is_hr())));
create policy "notifications own" on public.notifications for select using (user_id=auth.uid()); create policy "notifications update own" on public.notifications for update using (user_id=auth.uid());
create policy "audit hr" on public.audit_logs for select using (organization_id=current_org_id() and is_hr());
